[package]
name = "preview"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus.workspace = true
dioxus-blocks.workspace = true

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
